version: '3'


services:
  backend_webserver:
    build: ./webserver
    volumes:
      - ./webserver:/usr/src/app
    ports:
      - "5000:5000"
    networks:
      app-network:
        ipv4_address: 172.30.0.10
    container_name: webserver

  database:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      app-network:
        ipv4_address: 172.30.0.20
    container_name: database


networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16